#!/bin/sh

echo "Installing programs..."

REQUIRED_PKG="whiptail"
PKG_OK=$(dpkg-query -W --showformat='${Status}\n' $REQUIRED_PKG|grep "install ok installed")
echo Checking for $REQUIRED_PKG: $PKG_OK
if [ "" = "$PKG_OK" ]; then
  echo "No $REQUIRED_PKG. Setting up $REQUIRED_PKG."
  sudo apt-get --yes install $REQUIRED_PKG
fi

#message="Server Setup Script - Pick an option:."
#whiptail --msgbox --title "Wizard" "$message" 25 80


check_root(){
if [ "$(whoami)" != "root" ]; then
whiptail --msgbox --fb "Sorry you are not root!" "$WT_HEIGHT" "$WT_WIDTH"
        exit
#else
#whiptail --msgbox --fb "You are root!" "$WT_HEIGHT" "$WT_WIDTH"
fi
}

calc_wt_size() {
  WT_HEIGHT=17
  WT_WIDTH=$(tput cols)
  if [ -z "$WT_WIDTH" ] || [ "$WT_WIDTH" -lt 60 ]; then
    WT_WIDTH=80
  fi
  if [ "$WT_WIDTH" -gt 178 ]; then
    WT_WIDTH=120
  fi
  WT_MENU_HEIGHT=$((WT_HEIGHT-7))
}
spinner() {
  i=1
  while read -r line; do
    i=$(( i + 1 ))
    echo $i
    sleep 0.1
  done
}

check_root

systemclear() {
apt-get -y autoremove | spinner | whiptail --title "Removing Completly MySQL installattion and Databases" --gauge "Removing ...." 6 60 0
sudo apt-get -y autoclean | spinner | whiptail --title "Removing Completly MySQL installattion and Databases" --gauge "Removing ...." 6 60 0
}

systemupdate() {
#apt-get install -y mysql-server | spinner | whiptail --title "Installing MySQL server for Debian" --gauge "Please wait ..." 6 60 0
apt-get update | spinner | whiptail --title "APT update" --gauge "Please wait while apt update..." 6 60 0
}

ubuntu_initialize() {
	echo "Updating and Installing Dependicies"
	apt-get -qq update > /dev/null 2>&1
	apt-get -qq -y upgrade > /dev/null 2>&1
	apt-get install -qq -y nmap > /dev/null 2>&1
	apt-get install -qq -y git > /dev/null 2>&1
	rm -r /var/log/exim4/ > /dev/null 2>&1

	update-rc.d nfs-common disable > /dev/null 2>&1
	update-rc.d rpcbind disable > /dev/null 2>&1

	echo "IPv6 Disabled"

	cat <<-EOF >> /etc/sysctl.conf
	net.ipv6.conf.all.disable_ipv6 = 1
	net.ipv6.conf.default.disable_ipv6 = 1
	net.ipv6.conf.lo.disable_ipv6 = 1
	net.ipv6.conf.eth0.disable_ipv6 = 1
	net.ipv6.conf.eth1.disable_ipv6 = 1
	net.ipv6.conf.ppp0.disable_ipv6 = 1
	net.ipv6.conf.tun0.disable_ipv6 = 1
	EOF

	sysctl -p > /dev/null 2>&1

#	echo "Changing Hostname"
#	read -p "Enter your hostname: " -r primary_domain
NAME=$(whiptail --inputbox "What is your name?" 8 39 --title "Getting to know you" 3>&1 1>&2 2>&3)
exitstatus=$?
if [ $exitstatus = 0 ]; then
echo "Greetings," $NAME
else
echo "User canceled input."
fi

echo "(Exit status: $exitstatus)"
	cat <<-EOF > /etc/hosts
	127.0.1.1 $NAME $NAME
	127.0.0.1 localhost
	EOF

	cat <<-EOF > /etc/hostname
	$NAME
	EOF

	echo "The System will now reboot!"
#	reboot
}



while [ 1 ]
do
CHOICE=$(
whiptail --title "Server setup wizard" --menu "Make your choice" 16 100 9 \
	"1)" "Setup SSH."   \
	"2)" "Ubuntu Initializer."  \
	"9)" "End script"  3>&2 2>&1 1>&3	
)

result=$(whoami)
case $CHOICE in
	"1)")   
		result="I"
		check_root
	;;
	"2)") 
		OP=$(uptime | awk '{print $3;}') 
		ubuntu_initialize 
		OP1=$(uptime | awk '{print $3;}') 
		OP2=OP1-OP
		result="This system has been up $OP2 minutes"
	;;
        "9)") exit
        ;;
esac
whiptail --msgbox "$result" 20 78
done
exit
